### ISSUE TITLE
ENH: Move empirical models used by pysat_sgp4 into separate methods files

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatMissionPlanning#1]
Migrating from pysat/pysat#205.

Right now, sgp4 accesses pyglow to add simulated data from iri, msis, etc to the simulated instrument. These methods would be useful for to compare to measured data.

Proposal:

 - Add a pyglow_methods.py file to contain the pyglow functions currently incorporated in pysat_sgp4
 - Add an apexpy methods file for similar reasons
 - Add an aacgmv2 methods file, etc.
 - Add a brief tutorial on how to apply these functions to spacecraft data to the documentation section

**Comment by rstoneback** [comment]
Now that this is its own package, I think we should move the minimum pysat_sgp4 code to its own sub-directory (minimizes risk that pysat imports non-instrument files). All of the methods to add data to a pysat Instrument should be moved to the top level. Perhaps move the methods into a new file, _core.py that gets imported by init.

**Comment by jklenzing** [comment]
Here's my proposed breakdown, following how pysat is structured:

- pysatMissionPlanning
  - instruments
    - pysat_sgp4.py
  - methods
    - aacgmv2.py
    - apexpy.py
    - pyglow.py

**Comment by jklenzing** [comment]
Closing with merge of #9
